import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Camera, Plus, Trash2 } from "lucide-react";
import { type FormEvent, useState } from "react";
import { useParams } from "react-router-dom";
import { getErrorMessage } from "../api/client";
import { createSnapshot } from "../api/snapshots";
import { deleteManualBalance, getManualBalances, getWallet, saveManualBalances } from "../api/wallets";
import { PageState } from "../components/PageState";
import { SectionHeader } from "../components/SectionHeader";
import { formatUsd, shortAddress } from "../lib/format";
export function WalletDetail() {
  const queryClient = useQueryClient(); const walletId = Number(useParams().walletId); const [symbol, setSymbol] = useState(""); const [amount, setAmount] = useState(""); const [priceUsd, setPriceUsd] = useState("");
  const walletQuery = useQuery({ queryKey: ["wallet", walletId], queryFn: () => getWallet(walletId), enabled: Number.isFinite(walletId) });
  const balancesQuery = useQuery({ queryKey: ["wallet", walletId, "balances"], queryFn: () => getManualBalances(walletId), enabled: walletQuery.data?.wallet_type === "manual" });
  const snapshotMutation = useMutation({ mutationFn: () => createSnapshot(walletId), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["portfolio"] }); queryClient.invalidateQueries({ queryKey: ["wallet", walletId] }); } });
  const saveMutation = useMutation({ mutationFn: (payload: Parameters<typeof saveManualBalances>[1]) => saveManualBalances(walletId, payload), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["wallet", walletId, "balances"] }) });
  const deleteMutation = useMutation({ mutationFn: (assetId: number) => deleteManualBalance(walletId, assetId), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["wallet", walletId, "balances"] }) });
  if (walletQuery.isLoading) return <PageState title="Загружаем кошелек" />; if (walletQuery.isError || !walletQuery.data) return <PageState title="Кошелек не найден" />; const wallet = walletQuery.data;
  function handleAddBalance(event: FormEvent) { event.preventDefault(); const existing = balancesQuery.data?.balances.map((balance) => ({ symbol: balance.symbol, chain: balance.chain, amount: balance.amount, price_usd: balance.price_usd ?? null })) ?? []; saveMutation.mutate({ balances: [...existing, { symbol, chain: "manual", amount, price_usd: priceUsd || null }] }); setSymbol(""); setAmount(""); setPriceUsd(""); }
  return <section className="content-band"><SectionHeader eyebrow={wallet.wallet_type} title={wallet.label} actions={wallet.wallet_type === "evm" ? <button className="primary-button" type="button" onClick={() => snapshotMutation.mutate()} disabled={snapshotMutation.isPending}><Camera size={18} />{snapshotMutation.isPending ? "Снимаем..." : "Снапшот"}</button> : null} /><div className="detail-grid"><p><b>Адрес:</b> {shortAddress(wallet.address)}</p><p><b>Сеть:</b> {wallet.chain_type}</p><p><b>Статус:</b> {wallet.is_active ? "active" : "archived"}</p></div>{snapshotMutation.isError ? <p className="form-error">{getErrorMessage(snapshotMutation.error)}</p> : null}{wallet.wallet_type === "manual" ? <section className="nested-section"><SectionHeader eyebrow="Manual" title={`Балансы ${formatUsd(balancesQuery.data?.total_usd)}`} /><form className="inline-form" onSubmit={handleAddBalance}><input value={symbol} onChange={(e) => setSymbol(e.target.value.toUpperCase())} placeholder="BTC" required /><input value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Amount" required /><input value={priceUsd} onChange={(e) => setPriceUsd(e.target.value)} placeholder="Price USD" /><button className="primary-button" type="submit"><Plus size={18} />Сохранить</button></form>{saveMutation.isError ? <p className="form-error">{getErrorMessage(saveMutation.error)}</p> : null}<div className="table-list">{(balancesQuery.data?.balances ?? []).map((balance) => <article className="table-row" key={balance.asset_id}><div><strong>{balance.symbol}</strong><span>{balance.amount} · {balance.chain}</span></div><b>{formatUsd(balance.value_usd)}</b><button className="icon-button danger" type="button" onClick={() => deleteMutation.mutate(balance.asset_id)} aria-label="Удалить актив"><Trash2 size={17} /></button></article>)}</div></section> : <p className="muted">Для EVM-кошелька доступны снапшоты on-chain балансов.</p>}</section>;
}
