import { apiFetch } from "./client";
import type { ChainType, ManualBalancesRead, WalletRead, WalletType } from "./types";
export type WalletPayload = { label: string; wallet_type: WalletType; chain_type: ChainType | string; address?: string | null; group_id?: number | null; notes?: string };
export type WalletPatch = Partial<Pick<WalletRead, "label" | "group_id" | "is_active" | "notes" | "chain_type" | "address">>;
export type ManualBalancePayload = { balances: Array<{ symbol: string; chain?: string; amount: string; price_usd?: string | null }> };
export const getWallets = (activeOnly = true) => apiFetch<WalletRead[]>(`/wallets?active_only=${activeOnly}`);
export const getWallet = (id: number) => apiFetch<WalletRead>(`/wallets/${id}`);
export const createWallet = (payload: WalletPayload) => apiFetch<WalletRead>("/wallets", { method: "POST", body: JSON.stringify(payload) });
export const updateWallet = (id: number, payload: WalletPatch) => apiFetch<WalletRead>(`/wallets/${id}`, { method: "PATCH", body: JSON.stringify(payload) });
export const archiveWallet = (id: number) => apiFetch<WalletRead>(`/wallets/${id}`, { method: "DELETE" });
export const getManualBalances = (id: number) => apiFetch<ManualBalancesRead>(`/wallets/${id}/balances`);
export const saveManualBalances = (id: number, payload: ManualBalancePayload) => apiFetch<ManualBalancesRead>(`/wallets/${id}/balances`, { method: "PUT", body: JSON.stringify(payload) });
export const deleteManualBalance = (walletId: number, assetId: number) => apiFetch<void>(`/wallets/${walletId}/balances/${assetId}`, { method: "DELETE" });
